#!/usr/bin/env bash

grep -m 1 "<version>.*</version>" ${HAZELCAST_HOME}/pom.xml | awk -F'[><]' '{print $3}'

#mvn -f "${HAZELCAST_HOME}/pom.xml" org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['
