#!/usr/bin/env bash

filePattern=dstat.csv
title=${1:-dstat}

	##  THE command      dstat -tciymn --socket --tcp -rsgd

	#----system----     
	#    1
	#system-date-time

	#----total-cpu-usage----
	#    2                    3                     4                5                     6                  7
	#total-cpu-usage-usr total-cpu-usage-sys total-cpu-usage-idl total-cpu-usage-wai total-cpu-usage-hiq total-cpu-usage-siq

	#----interrupts---
	#     8              9             10
	#interrupts-33 interrupts-35 interrupts-36 

	#---system--
	#     11                        12
	# system-interrupts   system-context-switches 

	#------memory-usage-----
	#13     14    15     16
	#used  buff  cach  free

	#-net/total-
	#  17     18
	# recv  send

	# ------sockets------
	# 19  29  21  22  23
	# tot tcp udp raw frg

	#----tcp-sockets----
	# 24  25  26  27 28
	#lis act syn tim clo
	
	#--io/total-
	# 29    30
	# read  writ

	#----swap---
	# 31    32
 	#used  free
	
	#---paging--
	# 33   34
	# in   out

	#-dsk/total-
	# 35    36
	#read  writ

plotDstatCsv ${filePattern} 2 ${title} total-cpu-usage-usr
plotDstatCsv ${filePattern} 3 ${title} total-cpu-usage-sys
plotDstatCsv ${filePattern} 4 ${title} total-cpu-usage-idl
plotDstatCsv ${filePattern} 5 ${title} total-cpu-usage-wait
plotDstatCsv ${filePattern} 6 ${title} total-cpu-usage-hardw-interrupt
plotDstatCsv ${filePattern} 7 ${title} total-cpu-usage-softw-interrupt

plotDstatCsv ${filePattern} 8 ${title} interrupts-33
plotDstatCsv ${filePattern} 9 ${title} interrupts-35
plotDstatCsv ${filePattern} 10 ${title} interrupts-35 interrupts-36

plotDstatCsv ${filePattern} 11 ${title} system-interrupts
plotDstatCsv ${filePattern} 12 ${title} system-context-switches

plotDstatCsv ${filePattern} 13 ${title} memory-usage-used
plotDstatCsv ${filePattern} 14 ${title} memory-usage-buff
plotDstatCsv ${filePattern} 15 ${title} memory-usage-cach
plotDstatCsv ${filePattern} 16 ${title} memory-usage-free

plotDstatCsv ${filePattern} 17 ${title} net-total-recv
plotDstatCsv ${filePattern} 18 ${title} net-total-send

plotDstatCsv ${filePattern} 19 ${title} sockets-total
plotDstatCsv ${filePattern} 20 ${title} sockets-tcp
plotDstatCsv ${filePattern} 21 ${title} sockets-udp
plotDstatCsv ${filePattern} 22 ${title} sockets-raw
plotDstatCsv ${filePattern} 23 ${title} sockets-ip-fragments

plotDstatCsv ${filePattern} 24 ${title} tcp-sockets-listen
plotDstatCsv ${filePattern} 25 ${title} tcp-sockets-active
plotDstatCsv ${filePattern} 26 ${title} tcp-sockets-syn
plotDstatCsv ${filePattern} 27 ${title} tcp-sockets-time-wait
plotDstatCsv ${filePattern} 28 ${title} tcp-sockets-close

plotDstatCsv ${filePattern} 29 ${title} io-total-read
plotDstatCsv ${filePattern} 30 ${title} io-total-writ

plotDstatCsv ${filePattern} 31 ${title} swap-used
plotDstatCsv ${filePattern} 32 ${title} swap-free

plotDstatCsv ${filePattern} 33 ${title} paging-in
plotDstatCsv ${filePattern} 34 ${title} paging-out

plotDstatCsv ${filePattern} 35 ${title} disk-total-read
plotDstatCsv ${filePattern} 36 ${title} disk-total-writ
