#!/usr/bin/env bash

filePattern=$1
title=$2
ytitle=$3


#  1     2     3       4            5                 6                   7                8        9        10            11     12            13
#Date, Ticks, Count, Mean-Rate, One-Minute-Rate, Five-Minute-Rate, Fifteen-Minute-Rate, Rate-Unit, Last, Last-User-Value, Min, Min-User-Value, Max, 
#   14            15     16     17     18   19   20   21
#Max-User-Value, Mean, StdDev, Median, 75%, 95%, 98%, 99%,


#1   2      3    4     5     6      7    8    9    10   11  12    13         14       15        16       17           18
#t, count, max, mean, min, stddev, p50, p75, p95, p98, p99, p999, mean_rate, m1_rate, m5_rate, m15_rate, rate_unit, duration_unit



plotMetricsNoTime ${filePattern} 2 ${title} count
plotMetricsNoTime ${filePattern} 13 ${title} mean-rate
plotMetricsNoTime ${filePattern} 14 ${title} 1min-rate
plotMetricsNoTime ${filePattern} 15 ${title} 5min-rate
plotMetricsNoTime ${filePattern} 16 ${title} 15min-rate

plotMetricsNoTime ${filePattern} 5 ${title} min-latency
plotMetricsNoTime ${filePattern} 3 ${title} max-latency
plotMetricsNoTime ${filePattern} 4 ${title} mean-latency
plotMetricsNoTime ${filePattern} 6 ${title} stdDev-latency

plotMetricsNoTime ${filePattern} 8 ${title} 75-latency-percentile
plotMetricsNoTime ${filePattern} 9 ${title} 95-latency-percentTile
plotMetricsNoTime ${filePattern} 10 ${title} 98-latency-percentTile
plotMetricsNoTime ${filePattern} 11 ${title} 99-latency-percentTile
plotMetricsNoTime ${filePattern} 12 ${title} 999-latency-percentTile
