#!/usr/bin/env bash

FILE_PATTERN=$1
idx=$2
title=$3
yAxisTitle=$4

files=$(find . -name ${FILE_PATTERN} | xargs -n1 -I% echo -n " \"%\" using $idx with lines,")

files="${files%?}"

cat > plotScript << EOF

set datafile separator ","
set datafile commentschars '#!"'

set xlabel "report time step"
set ylabel "${yAxisTitle}"
set title "${title}"

set terminal png enhanced size 1280,1024
set output "${title}-${yAxisTitle}.png"
set key left top
plot $files

EOF

gnuplot plotScript

