#!/bin/bash

boxCount=2
memberBox=0
members=2
clients=2
duration=1h
ee=false
machienSpec=""
workingDir="workingHome"

OPTS=`getopt -o : --long  boxCount:,memberBox:,members:,clients:,duration:,ee:,machienSpec: -n 'parse-options' -- "$@"`
 
if [ $? != 0 ] ; then echo "Failed parsing options." >&2 ; exit 1 ; fi
 
eval set -- "$OPTS"
  
while true; do
  case "$1" in
    --ee ) ee="$2"; shift 2 ;;
    --boxCount ) boxCount="$2"; shift 2 ;;
    --memberBox ) memberBox="$2"; shift 2 ;; 
    --members ) members="$2"; shift 2 ;;
    --clients ) clients="$2"; shift 2 ;;
    --duration ) duration="$2"; shift 2  ;;
    --machienSpec ) machienSpec="$2"; shift 2  ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

if ! update-stabilizer ; then
   exit 1
fi
 
if ! update-hazelcast ; then
   exit 1
fi

if [ "$ee" == "true" ]; then 
 if ! update-hazelcast-ee ; then
   exit 1
 fi
 sed -i s/'<!--license-key-->'/"${HAZELCAST_EE_KEY}"/g $SIMULATOR_HOME/conf/hazelcast.xml
 sed -i s/'<!--license-key-->'/"${HAZELCAST_EE_KEY}"/g $SIMULATOR_HOME/conf/client-hazelcast.xml
fi

mkdir -p ${workingDir}

cp $SIMULATOR_HOME/stabilizer-tests/*.properties ${workingDir}
cp ~/run.sh ${workingDir}

output="$(pwd)/archive/$(date '+%Y_%m_%d-%H_%M_%S')"

cd ${workingDir}

hzVersion=$(getHazelcastVersion)
sed -i s/maven=.*/maven="${hzVersion}"/ simulator.properties

if [ -n "${machienSpec}" ]; then
  sed -i "s|MACHINE_SPEC=.*|MACHINE_SPEC=${machienSpec}|" simulator.properties
fi

./run.sh ${boxCount} ${memberBox} ${members} ${clients} ${duration} ${ee} ${output}

exit $?
