#!/usr/bin/env bash

ip=$1
from=$2
to=$3
user=${4:-$(whoami)}

simUser=$(grep -oh USER.* simulator.properties 2>/dev/null | cut -d = -f2)

if [ -n "${simUser}" ] ; then
 user="${simUser}"
fi

mkdir -p ${to}/${ip}/
scp -r ${user}@$ip:$from ${to}/${ip}/

