#!/usr/bin/env bash

agentsfile=${1:-agents.txt}

sshAll "ls" 2>&1 >/dev/null | grep -B 1 "Permission denied" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" > badAgents.txt

cat badAgents.txt | xargs -n1 -I% grep % agents.txt  > agent_KillList.txt
cat badAgents.txt | xargs -n1 -I% sed -i /%/d agents.txt

mv agents.txt temp_old_agents.txt
mv agent_KillList.txt agents.txt

provisioner --terminate

mv temp_old_agents.txt agents.txt
