#!/bin/sh

hzBranch=${1:-master}

git -C "${HAZELCAST_HOME}" remote update
git -C "${HAZELCAST_HOME}" checkout "${hzBranch}"

res=$(git -C "${HAZELCAST_HOME}" pull)

echo "Hazelcast $res"

if [ "$res" == "Already up-to-date." ] ; then
  exit 0
fi


if ! mvn -f "${HAZELCAST_HOME}/pom.xml" clean install -DskipTests ; then
  exit 1
fi

