#!/bin/sh

if ! git -C "${SIM_EE_TEST_HOME}" pull; then
	exit 1
fi

if ! mvn -f "${SIM_EE_TEST_HOME}/pom.xml" -U clean install -DskipTests ; then
	exit 1
fi 

cp $SIM_EE_TEST_HOME/ee-tests/target/*.jar  $SIMULATOR_HOME/user-lib/




