#!/bin/sh

if ! git -C "${SIMULATOR_ROOT}" pull; then
	exit 1
fi

if ! mvn -f "${SIMULATOR_ROOT}/pom.xml" -U clean install -DskipTests ; then
	exit 1
fi 

version=$(mvn -f "${SIMULATOR_ROOT}/pom.xml" org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\[')

rm -fr $SIMULATOR_HOME
unzip  -q ~/hazelcast-simulator/dist/target/hazelcast-simulator-${version}-dist.zip -d $HOME

sed -i s/SIMULATOR_VERSION=.*/SIMULATOR_VERSION=${version}/g ~/.bashrc
source ~/.bashrc




