#!/usr/bin/env bash

redFiles=$1
blueFiles=$2
idx=$3
title=$4
yAxisTitle=$5
keyState=${6:-on}

red=$(find . -name ${redFiles} | xargs -n1 -I% echo -n " \"%\" using 1:$idx with lines lt rgb \"red\",")
blue=$(find . -name ${blueFiles} | xargs -n1 -I% echo -n " \"%\" using 1:$idx with lines lt rgb \"blue\",")

red="${red%?}"
blue="${blue%?}"

cat > plotScript << EOF

set datafile separator ","
set datafile commentschars '#!"'

set xdata time
set timefmt "%s"
set format x "%H:%M:%S"

set xlabel "Time"
set ylabel "${yAxisTitle}"
set title "${title}"

set terminal png enhanced size 1280,1024
set output "${title}-${yAxisTitle}.png"

set key ${keyState}
set key left top
plot $red , $blue

EOF

gnuplot plotScript
