#!/bin/bash

set -e

cleanup() {
    exitCode=$?
    provisioner --terminate || true

    hear=$(pwd | grep -oh workspace.*)
    echo http://54.87.52.100/~jenkins/${hear}
    if (( $exitCode != 0 )) ; then 
      slackPost simulator-fail FAIL \<http://54.87.52.100/~jenkins/${hear}\>
    fi
    exit $exitCode
}

trap "cleanup" INT TERM EXIT

boxCount=2
memberBox=0
members=2
clients=2
duration=1h
ee=false
machienSpec=""
testDir=""
hazelcastVersion="master"
simulatorVersion='master'
lab="false"

OPTS=`getopt -o : --long  boxCount:,memberBox:,members:,clients:,duration:,ee:,machienSpec:,testDir:,hazelcastVersion:,simulatorVersion:,lab: -n 'parse-options' -- "$@"` || { echo "Failed parsing options." >&2 ; exit 1; }

initCmdArgs () { 
 eval set -- "$OPTS"
  
 while true; do
  case "$1" in
    --ee ) ee="$2"; shift 2 ;;
    --boxCount ) boxCount="$2"; shift 2 ;;
    --memberBox ) memberBox="$2"; shift 2 ;; 
    --members ) members="$2"; shift 2 ;;
    --clients ) clients="$2"; shift 2 ;;
    --duration ) duration="$2"; shift 2  ;;
    --machienSpec ) machienSpec="$2"; shift 2  ;;
    --testDir ) testDir="$2"; shift 2  ;;
    --hazelcastVersion ) hazelcastVersion="$2"; shift 2  ;;
    --simulatorVersion ) simulatorVersion="$2"; shift 2  ;;
    --lab ) lab="$2"; shift 2 ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
 done
}

updateRepos () {
 update-simulator ${simulatorVersion}
 update-hazelcast ${hazelcastVersion}
      
 if [ "$ee" == "true" ]; then 
    update-hazelcast-ee ${hazelcastVersion} build
 fi

 update-eeTests
}

setDirStruct () {
 output="$(pwd)/$(getHazelcastVersion)/$(date '+%Y_%m_%d-%H_%M_%S')"
 mkdir -p ${output}
 cp agents.txt ${output} 2>/dev/null || true
 cd ${output}
}

setSimulatorProps () {
 cp $SIMULATOR_HOME/simulator-tests/*.properties .
 cp ~/configuration/run .
 cp ~/configuration/simulator.properties .

 if [ -n "${testDir}" ]; then
   cp -fr $SIM_EE_TEST_DIR/${testDir}/. .
 fi

 if [ "$lab" == "true" ]; then
   cp -fr ~/lab/. .
 fi 

 hzVersion=$(getHazelcastVersion)
 sed -i s/maven=.*/maven="${hzVersion}"/ simulator.properties

 if [ -n "${machienSpec}" ]; then
   sed -i "s|MACHINE_SPEC=.*|MACHINE_SPEC=${machienSpec}|" simulator.properties
 fi
}

provisionBoxes () {
 awsCreate ${boxCount} jenkins-ec2-key
 provisioner --install
 provisioner --clean
}

mainFunction () {
 initCmdArgs
 updateRepos
 setDirStruct
 setSimulatorProps
 provisionBoxes

 ./run ${boxCount} ${memberBox} ${members} ${clients} ${duration} ${ee} | tee sim-output.out  ||  exitCode=${PIPESTATUS[0]}

 lookForErrors
 exit $exitCode
}

mainFunction 
