#!/bin/bash


servers=3
drivers=1
machienSpec=""
subnet=""
serverIps=""
driverIps=""
hzTag="master"
igTag="master"
ee=""

version=""

remoteUser='ec2-user'

cleanup() {
    provisioner --terminate
    echo "end"
}

trap "cleanup" INT TERM EXIT

OPTS=`getopt -o : --long  servers:,drivers:,subnet:,machienSpec:,hzTag:,igTag:,ee: -n 'parse-options' -- "$@"`
if [ $? != 0 ] ; then echo "Failed parsing options." >&2 ; exit 1 ; fi

initCmdArgs () {
 eval set -- "$OPTS"

 while true; do
  case "$1" in
    --servers ) servers="$2"; shift 2 ;;
    --drivers ) drivers="$2"; shift 2 ;;
    --subnet ) subnet="$2"; shift 2 ;;
    --machienSpec ) machienSpec="$2";  shift 2 ;;
    --hzTag ) hzTag="$2"; shift 2 ;;
    --igTag ) igTag="$2"; shift 2 ;;
    --ee ) ee="$2"; shift 2 ;;
    * ) break ;;
  esac
 done
}

initBoxes () {
 sshAll 'cd yardstick-hazelcast; git remote update; git checkout -- .; git checkout master;  git pull; mvn clean install -DskipTests'
 sshAll 'cd yardstick-ignite; git remote update; git checkout -- .; git checkout master; git pull; mvn clean install -DskipTests'
}

setLatestIgnite () {
 update-ignite "${1}" build
 version=$(getIgniteVersion)

 sshAll 'rm yardstick-ignite/libs/ignite-aws*' ec2-user
 sshAll	'rm yardstick-ignite/libs/ignite-core*' ec2-user
 sshAll	'rm yardstick-ignite/libs/ignite-indexing*' ec2-user
 sshAll	'rm yardstick-ignite/libs/ignite-spring*' ec2-user

 forIpsIn agents.txt scpUp $(find ~/.m2 -name ignite-aws-${version}.jar) yardstick-ignite/libs ec2-user
 forIpsIn agents.txt scpUp $(find ~/.m2 -name ignite-core-${version}.jar) yardstick-ignite/libs ec2-user
 forIpsIn agents.txt scpUp $(find ~/.m2 -name ignite-indexing-${version}.jar) yardstick-ignite/libs ec2-user
 forIpsIn agents.txt scpUp $(find ~/.m2 -name ignite-spring-${version}.jar) yardstick-ignite/libs ec2-user
}

setLatestHazelcast () {
 sshAll 'rm yardstick-hazelcast/libs/hazelcast-*.jar' ec2-user

 update-hazelcast "${1}" build
 version=$(getHazelcastVersion)

 if [ "$ee" == "true" ]; then
   update-hazelcast-ee "${1}" build
   forIpsIn agents.txt scpUp $(find ~/.m2 -name hazelcast-enterprise-${version}.jar) yardstick-hazelcast/libs ec2-user
   forIpsIn agents.txt scpUp $(find ~/.m2 -name hazelcast-enterprise-client-${version}.jar) yardstick-hazelcast/libs ec2-user
 else
   forIpsIn agents.txt scpUp $(find ~/.m2 -name hazelcast-${version}.jar) yardstick-hazelcast/libs ec2-user
   forIpsIn agents.txt scpUp $(find ~/.m2 -name hazelcast-client-${version}.jar) yardstick-hazelcast/libs ec2-user
 fi
}

initSimulatorProperties () {
 cp ~/configuration/simulator.properties .
 if [ -n "${machienSpec}" ]; then
  sed -i "s|MACHINE_SPEC=.*|MACHINE_SPEC=${machienSpec}|" simulator.properties
 fi
}

setBenchMarkProps () {
 localRepo=$1
 remoteRepo=$2
 ver=$3

 benchMarkfile=""
 if [ "$ee" == "true" ]; then
  benchMarkfile=benchmark-ec2-hd.properties
 else
  benchMarkfile=benchmark-ec2.properties
 fi

 sed -i "s/SERVER_HOSTS=.*/SERVER_HOSTS=${serverIps}/" ${localRepo}/config/${benchMarkfile}
 sed -i "s/DRIVER_HOSTS=.*/DRIVER_HOSTS=${driverIps}/" ${localRepo}/config/${benchMarkfile}
 sed -i "s/REMOTE_USER=.*/REMOTE_USER=${remoteUser}/" ${localRepo}/config/${benchMarkfile}
 sed -i "s/VER_ID=.*/VER_ID=${ver}/" ${localRepo}/config/${benchMarkfile}

 forIpsIn agents.txt scpUp ${localRepo}/config/${benchMarkfile} ${remoteRepo}/config/ ec2-user
}

collectResults () {
 remoteRepo=$1
 forIpsIn agents.txt scpDown ${remoteRepo}/logs-\* yard-log ec2-user
 sshAll "rm -r ${remoteRepo}/logs-*" ec2-user

 forIpsIn agents.txt scpDown ${remoteRepo}/bin/results-\* yard-res ec2-user
 sshAll "rm -r ${remoteRepo}/bin/results-*" ec2-user

 forIpsIn agents.txt scpDown ${remoteRepo}/* all ec2-user
}

runYardstickHz () {
 setBenchMarkProps ${YARD_HZ} yardstick-hazelcast ${version}

 hzXmlFile=""
 benchMarkfile=""
 if [ "$ee" == "true" ]; then
  hzXmlFile=hazelcast-ec2-hd.xml
  benchMarkfile=benchmark-ec2-hd.properties
 else
  hzXmlFile=hazelcast-ec2.xml
  benchMarkfile=benchmark-ec2.properties
 fi

 hzClientXml=hazelcast-client-config.xml

 cp ${YARD_HZ}/config/${hzXmlFile} .
 cp ${YARD_HZ}/config/${hzClientXml} .

 initHzMembersXml agents.txt ${hzXmlFile}
 initHzKeyXml ${hzXmlFile}
 initHzClientXml ${hzClientXml}

 forIpsIn agents.txt scpUp ${hzXmlFile} yardstick-hazelcast/config/ ec2-user
 forIpsIn agents.txt scpUp ${hzClientXml} yardstick-hazelcast/config/ ec2-user

 forIpAt 1 agents.txt sshCmd "cd  yardstick-hazelcast/bin; ./benchmark-run-all.sh ../config/${benchMarkfile}" ec2-user
 collectResults yardstick-hazelcast
}

runYardstickIg () {
 setBenchMarkProps ${YARD_IG} yardstick-ignite ${version}

 benchMarkfile=""
 if [ "$ee" == "true" ]; then
  benchMarkfile=benchmark-ec2-hd.properties
 else
  benchMarkfile=benchmark-ec2.properties
 fi

 xmlFile=ignite-ec2-config.xml

 cp ${YARD_IG}/config/${xmlFile} .
 initIgMemberValauesXml agents.txt ${xmlFile}

 forIpsIn agents.txt scpUp ${xmlFile} yardstick-ignite/config/
 forIpAt 1 agents.txt sshCmd "cd  yardstick-ignite/bin; ./benchmark-run-all.sh ../config/${benchMarkfile}" ec2-user

 collectResults	yardstick-ignite
}

compairResults () {
 results=($(find -type d -name results-* | sort))
 $YARD_HZ/bin/jfreechart-graph-gen.sh -gm COMPARISON -i ${results[0]} ${results[1]}
}

runHazelcastVsIgnite () {
 
 setLatestIgnite ${igTag}
 runYardstickIg

 setLatestHazelcast ${hzTag}
 runYardstickHz
 
 compairResults
}

runHazelcastVsHazelcast () {
 setLatestHazelcast master
 runYardstickHz

 setLatestHazelcast ${hzTag}
 runYardstickHz

 compairResults
}

checkPerfRegresion () {
 for f in $(find . -name Results.html); do

  new=$(xidel -e '//html/body/div/div[1]/div[2]/div/div[1]/table/tbody/tr[1]/td[2]' ${f} | tr -d ",")
  old=$(xidel -e '//html/body/div/div[1]/div[2]/div/div[1]/table/tbody/tr[2]/td[2]' ${f} | tr -d ",")

  if (( $(bc <<< "$old > $new") == 1 )) ; then
   echo "old $old > new $new"

   there=$(echo $f | tr -d ".")
   there=${f:1}
   hear=$(pwd | grep -oh workspace.*)

   slackPost benchmark-regression WARN \<http://54.87.52.100/~jenkins/${hear}${there}\>
  fi
 done
}

output="$(date '+%Y_%m_%d-%H_%M_%S')"
mkdir -p ${output}
cp agents.txt ${output} &> /dev/null
cd ${output}


initCmdArgs
initSimulatorProperties

awsCreate $(( servers + drivers )) jenkins-ec2
initBoxes

serverIps=$(forPrivateIpsIn agents.txt echo | sed -n 1,${servers}p | linesByComma)
to=$((servers+1))
from=$((drivers+1))
driverIps=$(forPrivateIpsIn agents.txt echo | sed -n ${to},${from}p | linesByComma)


#mkdir -p hazelcastMaster-Vs-IgniteMaster
#cp agents.txt hazelcastMaster-Vs-IgniteMaster &> /dev/null
#cp simulator.properties hazelcastMaster-Vs-IgniteMaster &> /dev/null
#cd hazelcastMaster-Vs-IgniteMaster
#runHazelcastVsIgnite
#cd ..

#mkdir -p hazelcast-${hzTag}-Vs-IgniteMaster
#cp agents.txt hazelcast-${hzTag}-Vs-IgniteMaster &> /dev/null
#cp simulator.properties hazelcast-${hzTag}-Vs-IgniteMaster &> /dev/null
#cd hazelcast-${hzTag}-Vs-IgniteMaster
#runHazelcastVsIgnite ${hzTag}
#cd ..

mkdir -p hazelcastMaster-Vs-hazelcast-${hzTag}
cp agents.txt hazelcastMaster-Vs-hazelcast-${hzTag} &> /dev/null
cd hazelcastMaster-Vs-hazelcast-${hzTag}
runHazelcastVsHazelcast
checkPerfRegresion
cd ..
