#!/usr/bin/env bash

duration=$1

if [ $# -eq 0 ]; then
    echo "duration required e.g:  5m 6h 48h"; exit 1
fi


hzVersion=$(getHazelcastVersion)
echo "version to test ${hzVersion}"

function setup {

 ee=$1
 boxCount=$2
 memberBox=$3
 members=$4
 clients=$5
 clusterProfile=$6
 
 startBox=$7
 endBox=$8

        local="${hzVersion}/${ee}/${clusterProfile}"
    	mkdir -p ${local}
        cp ${SIMULATOR_HOME}/simulator-tests/test.properties ${local}/
        cp ~/configuration/simulator.properties ${local}/
        cp ~/configuration/run ${local}/

        if [ "$ee" == "ee" ]; then
          cp -fr $SIM_EE_TEST_DIR/ee-simulator-tests/. ${local}/
        fi
  
	sed -i s/'boxCount=$1'/boxCount=${boxCount}/g ${local}/run
        sed -i s/'memberBox=$2'/memberBox=${memberBox}/g ${local}/run
	sed -i s/'members=$3'/members=${members}/g ${local}/run
	sed -i s/'clients=$4'/clients=${clients}/g ${local}/run
	sed -i s/'duration=$5'/duration=${duration}/g ${local}/run

          sed -i s/'ee=$6'/ee=false/g ${local}/run

        if [ "$ee" == "ee" ]; then
          sed -i s/'ee=$6'/ee=true/g ${local}/run
	fi

        if [ "$clusterProfile" == "lab" ]; then
          cp ~/lab/* ${local}/
          sed -i -n ${startBox},${endBox}p ${local}/agents.txt
        fi

        sed -i s/'HAZELCAST_VERSION_SPEC=maven=???'/HAZELCAST_VERSION_SPEC=maven=${hzVersion}/g ${local}/simulator.properties
}

setup  os  4   0  4   8    small
setup  os  10  0  10  50   large
setup  os  25  0  25  100  xlarge

setup  ee  4   0  4   8    small
setup  ee  10  0  10  50   large
setup  ee  25  0  25  100  xlarge
setup  ee  7   0  7   700  lab 1 7
