#!/usr/bin/env bash

cmd=$1
user=${2:-$(whoami)}
file=${3:-agents.txt}

simUser=$(grep -oh USER.* simulator.properties 2>/dev/null | cut -d = -f2)

if [ -n "${simUser}" ] ; then
 user=${simUser}
fi

forIpsIn "${file}" sshCmd "${cmd}" "${user}"
